### ISSUE TITLE
prometheus.MustRegister(...) fails, when tests are started with `-race`

### ISSUE THREAD

**Issue by guettli** [syself/hetzner-cloud-controller-manager#56]
```
reset; go test -race  ./...
```

```
panic: duplicate metrics collector registration attempted

goroutine 341 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(...)
        /home/guettli/go/pkg/mod/github.com/prometheus/client_golang@v1.20.5/prometheus/registry.go:406
github.com/syself/hetzner-cloud-controller-manager/internal/metrics.Serve({0x273e39f, 0x5})
        /home/guettli/syself/hetzner-cloud-controller-manager/internal/metrics/metrics.go:41 +0x5ea
created by github.com/syself/hetzner-cloud-controller-manager/hcloud.newHcloudClient in goroutine 339
        /home/guettli/syself/hetzner-cloud-controller-manager/hcloud/cloud.go:127 +0x64a
FAIL    github.com/syself/hetzner-cloud-controller-manager/hcloud       1.105s
```

**Comment by guettli** [comment]
Setting env var HCLOUD_METRICS_ENABLED to `false` solved that.
